version: "3.7"

services: 
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: apicrud
    ports:
        - "3000:3000"
    volumes:
      - ".:/user/api"
  