version: "3.7"

services: 
  server:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: apicrud
    ports:
        - "3000:3000"
    volumes:
      - ".:/user/app"
  